title: "Mazard Records"
email: "contact@mazard-records.fr"
description: ""
url: "https://www.mazard-records.fr"
github_username: "mazard-records"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
collections:
  links:
    output: false